Fix the data going in body of the approve button call
Real-Dev-Squad/website-dashboard pull request #157
Opened 2022-04-26 16:39 UTC by ojas-elawadhi

2022-04-29 17:52 UTC, lakshayman commented on src/profile/script.js
> +      oldData[listItem] || (listItem === 'yoe' ? '' : '')
```suggestion
      oldData[listItem] || ''
```
```suggestion
      oldData[listItem] || (listItem === 'yoe' ? '' : '')
```

2022-04-29 17:53 UTC, lakshayman commented on src/profile/script.js
> +      newData[listItem] || (listItem === 'yoe' ? '' : '')
```suggestion
      newData[listItem] || ''
```

2022-04-29 17:53 UTC, lakshayman commented on src/profile/script.js
> +      newData[listItem] || (listItem === 'yoe' ? '' : '')
```suggestion
      newData[listItem] || ''
```

2022-04-29 20:54 UTC, lakshayman approved these changes
LGTM

2022-05-02 13:25 UTC, lakshayman commented
Don't merge it now
Merge it after these issues are solved
https://github.com/Real-Dev-Squad/website-backend/issues/579
https://github.com/Real-Dev-Squad/website-backend/issues/578
https://github.com/Real-Dev-Squad/website-backend/issues/577

2022-06-12 15:15 UTC, Neha reviewed
There are a few improvements that can be done:

1. All hardcoded content should be moved to constant files
2. The functions for creating DOM elements move them to separate Util functions. Follow the Single responsibility Model.
3. Move HTTP request also as util function

2022-06-12 15:15 UTC, Neha commented on src/profile/script.js
> +    li.innerText = `${formatPropertyField(listItem)}: ${getDataItem(
This can be a util function. Instead of writing it 2 times. Make a util function and re-use it.

2022-06-12 15:15 UTC, Neha commented on src/profile/script.js
>      const li = document.createElement('li');
Logic of  creating the DOM elements should be moved to util functions and reused them wherever is required

2022-06-12 15:15 UTC, Neha commented on src/profile/script.js
>        document.getElementById('loader').innerHTML = 'No Profile Diffs !!!';
Move the hardcoded content to `constant` file

2022-06-24 06:48 UTC, Neha requested changes

2022-06-24 06:48 UTC, Neha commented on src/profile/script.js
> +    document.getElementById('loader').innerHTML = 'No Profile Diffs !!!';
All content should come from the constant file

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +    const li = document.createElement('li');
Move createElement as a reusable method. This method will accept the HTML element name, content, attributes such as classname

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +  approveBtn.innerText = 'Approve';
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +    const reason = prompt('Reason for Approval');
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +      document.getElementById('cover-spin').style.display = 'block';
This can be handle by adding className rather than writing inline style

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +          alert('User Data Approved !!!');
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +          alert('Something went wrong. Please check console errors.');
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +        alert('Something went wrong. Please check console errors.');
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +        document.getElementById('cover-spin').style.display = 'none';
Use add/remove class rather than adding inline style

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +        const response = await fetch(`${API_BASE_URL}/users/rejectDiff`, {
Move this to the reusable method. That will accept the URL, and type

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +          alert('User Data Rejected!!!');
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +          alert('Something went wrong. Please check console errors.');
Move the content to the constant

2022-06-24 06:48 UTC, Neha commented on src/profile/utils.js
> +        alert('Something went wrong. Please check console errors.');
Move the content to the constant

2022-07-09 19:18 UTC, ankushdharkar commented on src/profile/utils.js
> +//To GET self_user
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:18 UTC, ankushdharkar commented on src/profile/utils.js
> +//extracing wanted data from the data object
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:18 UTC, ankushdharkar commented on src/profile/utils.js
> +// creating a resuable card container component for showing multiple cards
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:18 UTC, ankushdharkar commented on src/profile/utils.js
> +//TO GET user from userid
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:18 UTC, ankushdharkar commented on src/profile/utils.js
> +  //looping through the old data to display in list
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:19 UTC, ankushdharkar commented on src/profile/utils.js
> +  //fixing footer at bottom to handle even if there is no data present
This comment can be skipped

2022-07-09 19:19 UTC, ankushdharkar commented on src/profile/utils.js
> +//function to create a card
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:19 UTC, ankushdharkar commented on src/profile/utils.js
> +//To display the list of data(old and new)
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:19 UTC, ankushdharkar commented on src/profile/utils.js
> +//to get the item from the data
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:19 UTC, ankushdharkar commented on src/profile/utils.js
> +//resusable function to extract the key property field and displaying the data
This comment adds no value. The function name seems to denote this already.

2022-07-09 19:19 UTC, ankushdharkar commented on src/profile/utils.js
> +//function to get the profile differences
This comment adds no value. The function name seems to denote this already.

2022-07-15 21:22 UTC, lakshayman approved these changes

2022-07-29 17:32 UTC, merged