Update/UI- changes in Button
Real-Dev-Squad/website-dashboard pull request #244
Opened 2022-11-08 23:35 UTC by theakashshukla

Improvement in Website template Button Ui 

✅ Tested

**Before**

![image](https://user-images.githubusercontent.com/49320497/200698064-0d861650-5634-45e9-b3c9-e79f5c34a1b8.png)

**After**

![image](https://user-images.githubusercontent.com/49320497/200698142-7c1f926e-9565-4f6f-9ec0-e1dcc54d5da6.png)

2022-12-12 14:52 UTC, prakashchoudhary07 requested changes

2022-12-12 14:52 UTC, prakashchoudhary07 commented on index.html
> +        onclick="location.href='src/online-members/online-members.html'"
Why are we adding a button for a link?
Why are we replacing the `<a>` tag with the `<button>` tag?

2022-12-12 14:52 UTC, prakashchoudhary07 commented on src/index.html
> +      </button>
Why are we replacing `<a>` tag `<button>` with?

2025-05-17 14:01 UTC, JC-Coder commented
@pankajjs 
kindly close 
reason - implemented already

2025-05-17 14:02 UTC, closed without merging