Added buttons for syncing
Real-Dev-Squad/website-dashboard pull request #414
Opened 2023-07-19 19:42 UTC by MayurLund

Issue #387 

Overview:
Added 2 buttons for syncing the data for discord users data and unverified Discord users data.

![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/37043221/d9bfaec3-52d3-4e0b-93b6-e78717776627)

2023-07-20 14:39 UTC, MayurLund commented on index.html
Hey @sahsisunny , Thanks for pointing out. I just noticed that now and moreover in the remaining file both the cases are used and its not consistent. So for now I will keep it to kebab case as majority of the code is in kebab case. To make the previous code casing consistent, should I make changes in this PR or create a new issue for that?

2023-07-20 15:16 UTC, gauravsinhaweb commented
@MayurLund  It would be nice if you could attach a working video of the implementation, and also provide a short description in the PR of what changes/ functionality you made in this PR

2023-07-20 19:43 UTC, MayurLund commented on index.html
Hey @sahsisunny Resolved that for my code. Please have a look at it.

2023-07-21 12:50 UTC, heyrandhir requested changes

2023-07-21 13:12 UTC, gauravsinhaweb approved these changes

2023-07-21 13:21 UTC, MayurLund commented on script.js
>  if (params.get('dev') === 'true') {
Hi @gauravsinhaweb I have not made these changes. Someone tried to test their functionality and pushed the changes too. So I am not making changes to those lines as they were previously present.

2023-07-21 23:16 UTC, sahsisunny approved these changes
Please link the ticket for test

2023-07-22 12:05 UTC, heyrandhir submitted a review, later dismissed

2023-07-23 05:30 UTC, MayurLund commented
> Please link the ticket for test
Created a new issue https://github.com/Real-Dev-Squad/website-dashboard/issues/422 for tests and linked up with the PR

2023-07-23 16:20 UTC, prakashchoudhary07 approved these changes

2023-07-23 16:22 UTC, merged