FEAT: added repo sync button and handlers
Real-Dev-Squad/website-dashboard pull request #427
Opened 2023-07-26 04:48 UTC by mailmesriza98

closes https://github.com/Real-Dev-Squad/website-dashboard/issues/425
Description:
Implement a "Repo Sync" button on the website dashboard. This button will trigger the synchronization of the repository with the staging environment by calling the Sync API. This button is should be behind a feature flag

![Screenshot 2023-07-29 135348](https://github.com/Real-Dev-Squad/website-dashboard/assets/22434603/9d0f8982-de3a-4718-8ad7-c102ed7fefbc)

![test](https://github.com/Real-Dev-Squad/website-dashboard/assets/22434603/48ac728c-383a-40f7-95fa-162ecb6fed40)

2023-07-27 04:57 UTC, Pratiyushkumar requested changes
Please follow proper format to raise PR by adding proper descriiption for reviewer and also write test and add test coverage to PR

2023-07-27 04:57 UTC, Pratiyushkumar commented on script.js
> +        toast.innerHTML = `<div class="message">✓ All repos uptodate</div>`;
can we `All repos uptodate` as constant and use it here please

2023-07-29 10:04 UTC, sahsisunny commented on style.css
Could you please create the variables for the color and specify the usage of REM instead of PX in case the value is less than 10PX?

2023-07-30 02:52 UTC, sahsisunny submitted a review, later dismissed

2023-07-31 14:05 UTC, vinit717 commented on style.css
> +}
Use px for smaller value

2023-07-31 14:05 UTC, vinit717 commented on style.css
> +  height: 0.06rem;
here also

2023-07-31 14:05 UTC, vinit717 commented on style.css
use px instead of rem for smaller value

2023-07-31 14:43 UTC, sahsisunny commented on style.css
> use px instead of rem for smaller value

https://github.com/Real-Dev-Squad/website-dashboard/pull/427#discussion_r1278281034

2023-08-01 00:38 UTC, sahsisunny approved these changes

2023-08-01 00:49 UTC, vinit717 commented on style.css
> +  height: 0.3rem;
still, for small values, you are using rem

2023-08-01 00:49 UTC, vinit717 commented on style.css
> +  right: 0.5rem;
+1

2023-08-01 01:10 UTC, vinit717 approved these changes

2023-08-01 12:31 UTC, Pratiyushkumar approved these changes
lgtm

2023-08-03 14:05 UTC, merged