dev to main sync
Real-Dev-Squad/website-dashboard pull request #581
Opened 2023-10-18 07:50 UTC by shritis98

**Developer Name:** @shritis98 

**PR Number(s):** 
-  https://github.com/Real-Dev-Squad/website-dashboard/pull/580

**Backend changes**

- [ ] Yes
- [x] No

**Frontend Changes**

- [x] Yes
- [ ] No        

**Database changes**

- [ ] Yes
- [x] No

**Breaking changes (If your feature is breaking/missing something please mention pending tickets)**

- [x] No
- [ ] Yes

**Deployment notes(Any special instructions for the deployment)**

- [x] No

**Tested in staging**

- [x] Yes
- [ ] No

Media to show changes
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/140648846/c0e3073c-56da-4320-a984-e014243a2621)

2023-10-18 10:02 UTC, iamitprakash submitted a review, later dismissed

2023-10-18 10:03 UTC, iamitprakash requested changes
Please resolve merge conflict

2023-10-18 21:00 UTC, lakshayman approved these changes

2023-10-21 03:16 UTC, ardourApeX commented
### Developer Name: Joy Gupta

### PR Number(s): 581

### Issue Ticket Number:
- https://github.com/Real-Dev-Squad/website-dashboard/issues/494

### Backend Changes
- [ ] Yes
- [x] No

### Frontend Changes
- [x] Yes
- [ ] No

### Is Under Feature Flag
- [x] Yes
- [ ] No

### Database changes: 
- [ ] Yes
- [x] No

### Breaking changes (If your feature is breaking/missing something please mention pending tickets): 
- [ ] Yes
- [x] No

### Deployment notes:
Please make sure the following composite index has been created in prod database : [IssueLink](https://github.com/Real-Dev-Squad/website-backend/issues/1621)
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/57b3065e-fea8-4e0b-8dbc-c821eddffad3)


### Tested in staging
- [x] Yes
- [ ] No

### List of PRs going in this Sync
- https://github.com/Real-Dev-Squad/website-backend/pull/1618

### Proposal Doc
- https://docs.google.com/document/d/1sf-BAs7C6wmfjRVS-82X492hcb_7jAfIM-7pWtizuXE/edit

### QA Instructions, Screenshots, Recordings

**1. Edit log must be generated when a super user updates the extension request under the dev flag**
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/a82f0727-1e65-402e-8c05-a79f692b8020)

**2. Should be backward compatible**
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/021243e3-1704-4173-b01d-4d558ec03269)

**3. Logs should not be visible outside the dev mode**
![image](https://github.com/Real-Dev-Squad/website-dashboard/assets/56365512/521986d3-6d19-4967-99a5-28cdee2b8edc)

2023-10-23 19:09 UTC, shritis98 commented
This PR got reverted and the changes have been made in a new PR

2023-10-23 19:09 UTC, closed without merging