add application button on home page for super user and added status field in application details
Real-Dev-Squad/website-dashboard pull request #669
Opened 2024-01-06 00:21 UTC by vinayak-trivedi

Date: 6/01/2024

## Description

This PR adds application button on home page for super user and also addds status field in application details page.

**Documentation Updated?**

-   [ ] Yes
-   [x] No

_If your feature adds a new API, then documentation related to the feature like API-Contracts, and Data-models  must be updated._

**Breaking Changes**

-   [ ] Yes
-   [x] No

_If your feature introduces breaking changes or if something is missing, please mention the related issue tickets._

**Development Tested?**

-   [x] Yes
-   [ ] No

_Confirm whether the changes have been tested locally during development._

**Tested in Staging?**

-   [ ] Yes
-   [x] No

_Indicate whether the changes have been tested in the staging environment._

**Under Feature Flag**

-   [ ] Yes
-   [x] No

_Specify if the changes are currently under a feature flag._

**Database Changes**

-   [ ] Yes
-   [x] No

2024-01-06 14:01 UTC, anishpawaskar requested changes
Please write test

2024-01-06 14:42 UTC, satyam73 commented
Please add a screenshot of the UI change

2024-01-09 00:06 UTC, anishpawaskar approved these changes

2024-01-09 00:12 UTC, vikhyat187 commented on index.html
> +        href="/applications"
Hi @vinayak-trivedi can we have a better naming here, I would not have been able to understand what application does, if this was viewed without any context by me.

2024-01-09 00:18 UTC, vikhyat187 commented on index.html
> +        href="/applications"
Discussed this, it takes to Applications page.

2024-01-09 00:20 UTC, vikhyat187 approved these changes

2024-01-09 23:18 UTC, merged