Feat: UI for listing extension requests in /requests page
Real-Dev-Squad/website-dashboard pull request #774
Opened 2024-08-05 21:06 UTC by Achintya-Chatterjee

Date: 6th August 2024

Developer Name: @Achintya-Chatterjee 

---

## Issue Ticket Number

- Closes #756
## Description

- Integrated the extension request section in the /request page on the extension tab

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-08-09 02:49 UTC, sahsisunny commented
Based on the demo video you provided:

- The loader should be centered in the display, and even if it’s specific to the ER card, it should still be positioned in the center.
- The query parameter is not showing when you switch between tabs, such as from OOO to Extension.

2024-08-09 02:59 UTC, sahsisunny requested changes

2024-08-09 02:59 UTC, sahsisunny commented on requests/util.js
> +  });
We have the `/requests` API available for all types of requests. Please use this API and refer to the API contract documentation for any related information.

2024-08-09 02:59 UTC, sahsisunny commented on requests/util.js
> +};
The `/requests` route does not include sorting options.

2024-08-09 02:59 UTC, sahsisunny commented on requests/util.js
> +  });
We also need to update this endpoint if we're using the `/requests` route.

2024-08-09 03:06 UTC, sahsisunny commented
### Here is the key difference between [old ](https://api.realdevsquad.com/extension-requests?order=asc&size=1)and [new ](https://staging-api.realdevsquad.com/requests?dev=true&type=EXTENSION)data
| **Attribute**       | **New**        | **Old**        |
|---------------------|-----------------------------|-------------------------------|
| **id**              | Present                      | Present                        |
| **createdAt**       | Present                      | Not Present                    |
| **requestedBy**     | Present                      | Not Present                    |
| **requestNumber**   | Present                      | Present                        |
| **newEndsOn**       | Present                      | Present                        |
| **oldEndsOn**       | Present                      | Present                        |
| **assignee**        | Present                      | Present                        |
| **type**            | Present                      | Not Present                    |
| **title**           | Present                      | Present                        |
| **message**         | Present                      | Not Present                    |
| **taskId**          | Present                      | Present                        |
| **lastModifiedBy**  | Present                      | Not Present                    |
| **state/status**    | Present (state)              | Present (status)               |
| **updatedAt**       | Present                      | Not Present                    |
| **reason**          | Not Present(same as `message`)                 | Present                        |
| **assigneeId**      | Not Present(same as `requestedBy`)                  | Present                        |
| **timestamp**       | Not Present(same as `createdBy` and `updatedat`)                  | Present                        |

2024-08-09 08:15 UTC, Achintya-Chatterjee commented
> Based on the demo video you provided:
> 
> * The loader should be centered in the display, and even if it’s specific to the ER card, it should still be positioned in the center.
> * The query parameter is not showing when you switch between tabs, such as from OOO to Extension.
> * The filters and search options are the same across all tabs, such as OOO, Task, and Extension, and are not specific to the Extension tab only.

@sahsisunny I didn't develop this UI, it was already been built by devanshu, I just raise the PR

2024-08-09 08:17 UTC, sahsisunny commented
> > Based on the demo video you provided:
> > 
> > * The loader should be centered in the display, and even if it’s specific to the ER card, it should still be positioned in the center.
> > * The query parameter is not showing when you switch between tabs, such as from OOO to Extension.
> > * The filters and search options are the same across all tabs, such as OOO, Task, and Extension, and are not specific to the Extension tab only.
> 
> @sahsisunny I didn't develop this UI, it was already been built by devanshu, I just raise the PR

I know @Achintya-Chatterjee . Your task is not only to be raise PR. You need also to do changes if required.

2024-08-09 09:22 UTC, Achintya-Chatterjee commented
> > > Based on the demo video you provided:
> > > 
> > > * The loader should be centered in the display, and even if it’s specific to the ER card, it should still be positioned in the center.
> > > * The query parameter is not showing when you switch between tabs, such as from OOO to Extension.
> > > * The filters and search options are the same across all tabs, such as OOO, Task, and Extension, and are not specific to the Extension tab only.
> > 
> > 
> > @sahsisunny I didn't develop this UI, it has already been built by Devanshu, I just raised the PR
> 
> I know @Achintya-Chatterjee . Your task is not only to raise PR. You also need to do changes if required.

@sahsisunny then how do you want the new extension request to be?

2024-08-15 17:58 UTC, Achintya-Chatterjee commented
> Based on the demo video you provided:
> 
> * The loader should be centered in the display, and even if it’s specific to the ER card, it should still be positioned in the center.
> * The query parameter is not showing when you switch between tabs, such as from OOO to Extension.
> * The filters and search options are the same across all tabs, such as OOO, Task, and Extension, and are not specific to the Extension tab only.

@sahsisunny there is no filter in OOO and Task.

2024-08-16 12:38 UTC, ashifkhn submitted a review, later dismissed

2024-08-16 20:06 UTC, ashifkhn approved these changes

2024-08-17 20:26 UTC, iamitprakash approved these changes

2024-08-17 21:40 UTC, merged