Improve Dashboard Site Homepage
Real-Dev-Squad/website-dashboard pull request #817
Opened 2024-09-07 18:12 UTC by Nikhil-Kumar1

Date:  07 Sep 2024

Developer Name:  Nikhil Kumar

## Issue Ticket Number:  #808

## Description
 Fixed styling of the Dashboard page and added description.

https://tubular-crostata-e9a09e.netlify.app/

2024-09-07 18:45 UTC, iamitprakash requested changes
Details are missing

2024-09-15 05:49 UTC, pallabez commented on style.css
> +} */
Can we remove this if we are not using this?

2024-09-15 06:00 UTC, pallabez commented
The cards font weight looks too strong. Can we take the reference from /groups?
<img width="295" alt="image" src="https://github.com/user-attachments/assets/8f58f7f4-98bb-47a0-9927-e98f48ff4663">


```
<div class="card">
        <h5 class="card__title">Too Much Truth</h5>
        <p class="card__description">Please ask the role creator or admin to update this group description.</p>
</div>
    
.card {
     background: var(--color-group-background);
     padding: 20px;
     border-radius: 15px;
     border: 1px solid hsla(0, 0%, 92%, 1);
     box-shadow: 1px 2px 4px 0px hsla(0, 0%, 0%, 0.1);
}

.card__title {
  font-size: 1.1rem;
  font-weight: 600;
}

.card__description {
  margin-top: 0.6rem;
  color: var(--color-text-secondary);
  font-weight: 400;
  font-size: 0.8rem;
  line-height: 18px;
}
```

2024-09-15 18:09 UTC, pallabez commented
Thanks for changing the font weight. Can we do the same for box shadow and font color? Also would recommend to remove the hover effect. What do you think?

2024-09-15 19:02 UTC, Nikhil-Kumar1 commented
Yes, I will do it

On Sun, 15 Sept, 2024, 23:39 Pallab Sonowal, ***@***.***>
wrote:

> Thanks for changing the font weight. Can we do the same for box shadow and
> font color? Also would recommend to remove the hover effect. What do you
> think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Real-Dev-Squad/website-dashboard/pull/817#issuecomment-2351708723>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBBQVZXUHFWDCH7GTSPQEZLZWXEOXAVCNFSM6AAAAABN2G74QOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJRG4YDQNZSGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-17 16:51 UTC, pallabez commented
Discussed 

```
      <a
        class="card"
        href="/goal/index.html"
        id="create-goal"
      >
        <h5 class="card__title">Create Goals</h5>
        <p class="card__description">
          Set and track goals to align efforts and measure progress.
        </p>
      </a>
```

```
.card {
  margin: 0;
  background-color: white;
  text-decoration: none;
  padding: 20px;
  width: 300px;
  border-radius: 15px;
  border: 1px solid hsla(0, 0%, 92%, 1);
  box-shadow: 1px 2px 4px 0px hsla(0, 0%, 0%, 0.1);
}

.card__title {
  font-size: 1.1rem;
  font-weight: 600;
  color: hsla(0, 0%, 21%, 1);
}

.card__description {
  margin-top: 0.6rem;
  color: hsla(0, 0%, 21%, 0.75);
  font-weight: 400;
  font-size: 0.8rem;
  line-height: 18px;
}

```

2024-09-20 04:21 UTC, pallabez approved these changes

2024-09-21 05:30 UTC, Nikhil-Kumar1 commented
> Details are missing

previously I had written commit01,02,03, but  after that I have started mentioning the details, could you please check once.

2024-09-21 09:40 UTC, merged