fix online-members page task section
Real-Dev-Squad/website-dashboard pull request #878
Opened 2024-10-08 14:57 UTC by Mir-SA

Date: 08/10/2024

Developer Name: Sameer Supe

---

## Issue Ticket Number

- Closes #876 

## Description

changed a value in script.js which was preventing task section from rendering, also changes a stylesheet value

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [ ] Yes
- [x] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [ ] Yes
- [x] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

https://github.com/user-attachments/assets/07009fc3-9158-439f-ae98-7b74f3a5a055

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-10-09 15:28 UTC, yesyash approved these changes

2024-10-10 06:53 UTC, vinit717 requested changes
Please fix the failing tests also Can we show spinner instead of Loading... text

2024-10-10 08:02 UTC, Mir-SA commented
> Please fix the failing tests 

 fixed it.

> also Can we show spinner instead of Loading... text

@vinit717 sure, should I send it in this pr? or raise another ticket?

2024-10-11 15:37 UTC, iamitprakash approved these changes

2024-10-11 15:38 UTC, merged