enhancement: added shimmer effect
Real-Dev-Squad/website-dashboard pull request #884
Opened 2024-10-12 10:06 UTC by rishirishhh

Date: 

Developer Name: 

---

## Issue Ticket Number

## Description

### Documentation Updated?

- [ ] Yes
- [ ] No

### Under Feature Flag

- [ ] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [ ] No

### Breaking Changes

- [ ] Yes
- [ ] No

### Development Tested?

- [ ] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

</details>

## Additional Notes

2024-10-12 16:23 UTC, joyguptaa commented on extension-requests/script.js
> +      statusSiteLink.classList.remove('skeleton-link');
nit : `assigneeNameElement.classList.toggle('skeleton-text', !dev);`

2024-10-12 16:23 UTC, joyguptaa commented on extension-requests/script.js
> +      statusSiteLink.classList.remove('skeleton-link');
ref : https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle

2024-10-12 16:24 UTC, joyguptaa commented on extension-requests/script.js
> +      statusSiteLink.classList.remove('skeleton-link');
same for line 1266, 1271, 1275

2024-10-12 16:24 UTC, joyguptaa commented on extension-requests/style.css
> +  width: 1.5rem; /* Adjust the width */
remove the comments from this file

2024-10-12 16:25 UTC, joyguptaa commented
The test Coverage Screenshot is not visible. Please Check

2024-10-12 16:55 UTC, rishirishhh commented
![Screenshot from 2024-10-12 22-25-05](https://github.com/user-attachments/assets/4d9bc79a-bb9f-4fe6-b80e-dc2015f6f779)
Test Coverage

2024-10-13 09:50 UTC, shubhdevelop commented
> ![Screenshot from 2024-10-12 22-25-05](https://private-user-images.githubusercontent.com/148757583/375972725-4d9bc79a-bb9f-4fe6-b80e-dc2015f6f779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTMyMjcsIm5iZiI6MTcyODgxMjkyNywicGF0aCI6Ii8xNDg3NTc1ODMvMzc1OTcyNzI1LTRkOWJjNzlhLWJiOWYtNGZlNi1iODBlLWRjMjAxNWY2Zjc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwOTQ4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMTFhYThjYzk0YmY0YjI1NTliMzJhNTczMjBlYjkzNzA5NDJkM2IyOTAwMjE2YjEzMWUxNTg0NjZhNmU1NWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J_8EkrGW2fYh3IGzglVieVFzW9mJH33MUJKItLhrHO8) Test Coverage

add it to the Pr description it's still not visible there

2024-10-15 08:35 UTC, Achintya-Chatterjee approved these changes

2024-10-15 18:09 UTC, shubhdevelop submitted a review, later dismissed

2024-10-15 18:30 UTC, joyguptaa commented
> ![Screenshot from 2024-10-12 22-25-05](https://private-user-images.githubusercontent.com/148757583/375972725-4d9bc79a-bb9f-4fe6-b80e-dc2015f6f779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTcyODgsIm5iZiI6MTcyOTAxNjk4OCwicGF0aCI6Ii8xNDg3NTc1ODMvMzc1OTcyNzI1LTRkOWJjNzlhLWJiOWYtNGZlNi1iODBlLWRjMjAxNWY2Zjc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxODI5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTI3MGYxMjZkMmIyMDM5YzQxNjI0Zjc3ZDM4YTkxZGQ0MDczMjdkMjk5YThjYTU3YWFiNDg0MmYxY2EyMGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ymvruwnIj_9-racdxHCe15vQMtShXSt1obupXYa2nTc) Test Coverage

Please add coverage screenshot for extension-requests/script.js file as it is not visible in the attached image.

2024-10-15 18:41 UTC, rishirishhh commented
> > ![Screenshot from 2024-10-12 22-25-05](https://private-user-images.githubusercontent.com/148757583/375972725-4d9bc79a-bb9f-4fe6-b80e-dc2015f6f779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTcyODgsIm5iZiI6MTcyOTAxNjk4OCwicGF0aCI6Ii8xNDg3NTc1ODMvMzc1OTcyNzI1LTRkOWJjNzlhLWJiOWYtNGZlNi1iODBlLWRjMjAxNWY2Zjc3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxODI5NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTI3MGYxMjZkMmIyMDM5YzQxNjI0Zjc3ZDM4YTkxZGQ0MDczMjdkMjk5YThjYTU3YWFiNDg0MmYxY2EyMGIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ymvruwnIj_9-racdxHCe15vQMtShXSt1obupXYa2nTc) Test Coverage
> 
> Please add coverage screenshot for extension-requests/script.js file as it is not visible in the attached image.

![Screenshot from 2024-10-16 00-10-41](https://github.com/user-attachments/assets/b4c44b8b-4c5b-4cd0-b4ba-b19186ccaac6)
Here is the image @joyguptaa

2024-10-15 18:41 UTC, joyguptaa submitted a review, later dismissed

2024-10-15 18:47 UTC, iamitprakash requested changes
make design uniform

2024-10-16 00:47 UTC, shubhdevelop commented
update the video in PR, reflecting latest changes

2024-10-16 13:47 UTC, iamitprakash approved these changes

2024-10-16 13:47 UTC, merged